# Site settings
title: KunChun Tsai | Khun-kin Tshuà
description: Software System Engineer
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: KunChunTsai 蔡昆均
user_description: I'm a software engineer and an engineering manager, experienced in mobile phone protocol stack, embedded system, computer vision and VR/AR products; responsible for architecture design, project managements and people managements. Also, I'm passionate about athlete performance training and worked in an university basketball team as a strength and conditioning instructor.
user_title: Software Developer
email: ee93chly@gmail.com
linkedin_username: kunchuntsai
instagram_username: kunchuntsai
calender_username: ee93chly

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
