# Site settings
title: KunChun Tsai | KhunKin Tshuà | 蔡昆均
description: Software System Engineer
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: KunChunTsai 蔡昆均
user_description: I am a software engineer and engineering manager with experience in mobile phone protocol stacks, embedded systems, computer vision, and VR/AR products. I am responsible for architecture design, project management, and people management. Additionally, I am passionate about athletic performance training and have worked as a strength and conditioning instructor for a university basketball team.
user_title: Software Developer
email: ee93chly@gmail.com
linkedin_username: kunchuntsai
instagram_username: kunchuntsai
calender_username: ee93chly

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
